name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (cached)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          tags: jekyll-site:latest
          load: true   # makes image available for docker run
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download required data
        run: |
          docker run --rm \
            -u root \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            jekyll-site:latest \
            Rscript -e "options(timeout=1900); \
                        dir.create('data', showWarnings=FALSE); \
                        download.file('https://ndownloader.figshare.com/files/18533342', './data/cc_variants.sqlite'); \
                        download.file('https://ndownloader.figshare.com/files/24607961', './data/mouse_genes.sqlite'); \
                        download.file('https://ndownloader.figshare.com/files/24607970', './data/mouse_genes_mgi.sqlite'); \
                        download.file('ftp://ftp.jax.org/dgatti/qtl2_workshop/qtl2_demo.Rdata', './data/qtl2_demo.Rdata');"


      - name: Run Jekyll build inside container
        run: |
          docker run --rm \
            -u root \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            jekyll-site:latest \
            make site

      - name: Remove oversized data files before deploy
        run: |
          rm -f _site/data/cc_multitissue_qtlviewer.Rdata
          rm -f _site/data/qtl2_demo.Rdata
          rm -f _site/data/cc_variants.sqlite
          rm -f _site/data/mouse_genes.sqlite
          rm -f _site/data/mouse_genes_mgi.sqlite

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
